name: Site

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Clone deploy repository
      run: git clone git@github.com:zeh-raiz/biblia-raiz-deploy.git

    - name: Run script
      run: bash biblia-raiz-deploy/deploy.sh